Renamed file Fixed log Now re-asking iso killing Bug fixes

diff --git a/soSsh b/soSsh
--- a/soSsh
+++ b/soSsh
@@ -26,7 +26,7 @@ function _jq() {
 }
 
 # Check JQ dependency
-hash "jq" 2>/dev/null || { printf >&2 "\n${red}\n\tDepeneancy error!${reset}\n\n\tsoSsh requires ${bold}jq{$reset} package!\n\n\t${green}Please install with ${bold}sudo apt install jq${green}!${reset}"; exit 2; }
+hash "jq" 2>/dev/null || { printf >&2 "\n${red}\n\tDependency error!${reset}\n\n\tsoSsh requires ${bold}jq{$reset} package!\n\n\t${green}Please install with ${bold}sudo apt install jq${green}!${reset}"; exit 2; }
 
 # Ensure json file exists
 if [ ! -f ~/.sossh ]; then
@@ -36,7 +36,7 @@ if [ ! -f ~/.sossh ]; then
 fi
 
 # Read JSON & Get some basics
-raw=`jq . "${_DIR}wCn.json"`
+raw=`jq . ~/.sossh`
 b_port=$(echo $raw | jq -r '.default.port // 22')
 b_user=$(echo $raw | jq -r '.default.user // "root"')
 b_rsub=$(echo $raw | jq -r '.default.rsub // false')
@@ -66,9 +66,14 @@ while [[ $reached_end == false ]]; do
         f_tmp=`echo ${last_while_obj} | jq ".g[]  | select(.id == ${input})"`
 
         # Retry or continue
-        [[ -z $f_tmp ]] && echo -e "\n${red}${bold}Group${reset}${red} not found!${reset}\n" && continue || last_while_obj="$f_tmp"
-        # [[ -z $f_tmp ]] && echo -e "\n${red}Server not found!${reset}\n" && continue
-
+        if [[ -z $f_tmp ]]; then
+            echo -e "\n${red}${bold}Group${reset}${red} not found!${reset}"
+            continue
+        else
+            ((depth++))
+            last_while_obj="$f_tmp"
+            continue
+        fi
     fi
 
     # S
@@ -101,7 +106,7 @@ while [[ $reached_end == false ]]; do
             g_b_name_c=$(echo ${g_b_name_c/\?\?/${red}X${reset}})
 
             # For .t times
-            echo -e "\n${prefix}${green}Select${reset} ${bold}${g_b_name_c}${reset} ${undl}server${reset}:\n"
+            echo -e "\n${prefix}    ${green}Select${reset} ${bold}${g_b_name_c}${reset} ${undl}server${reset}:\n"
             for (( i = 0; i < has_t; i++ )); do
 
                 # Create h_i (++)
@@ -115,7 +120,7 @@ while [[ $reached_end == false ]]; do
                 # Replace '??' --> $i
                 t_ip=$(echo ${t_ip/\?\?/$h_i})
                 t_name=$(echo ${t_name/\?\?/$h_i})
-                echo -e "${prefix}            ${h_i}${hk} ${t_name} ($t_ip)"
+                echo -e "${prefix}        ${h_i}${hk} ${t_name} ($t_ip)"
             done
 
             # Read and validate input until valid
@@ -130,7 +135,7 @@ while [[ $reached_end == false ]]; do
             done
 
             # Replace ?? with number
-            f_ip=$(echo ${g_b_ip/\?\?/$i})
+            f_ip=$(echo ${g_b_ip/\?\?/$input})
             f_name=$(echo ${g_b_name/\?\?/$input})
 
             # Set $f_s to custom object
